In [1]:
import pandas as pd

In [3]:
dataframe1 = pd.read_csv('data/ch16_20240522100101_v1.csv')
dataframe2 = pd.read_csv('data/ch16_20240522112543.csv')

In [4]:
dataframe1.head(5)

,frame_number,frame_time,results
0,0,2024/5/22 Wednesday 10:1:1,"[{'box': [1181.4295654296875, 897.904846191406..."
1,1,2024/5/22 Wednesday 10:1:1,"[{'box': [1281.750732421875, 920.2911376953125..."
2,2,2024/5/22 Wednesday 10:1:1,"[{'box': [1299.7904052734375, 923.881591796875..."
3,3,2024/5/22 Wednesday 10:1:1,"[{'box': [1304.3641357421875, 924.4345703125, ..."
4,4,2024/5/22 Wednesday 10:1:1,"[{'box': [1304.623046875, 924.5234375, 268.103..."

In [5]:
dataframe2.head()

,frame_number,frame_time,results
0,0,2024/5/22 Wednesday 11:25:43,"[{'box': [1651.468505859375, 360.8627014160156..."
1,3,2024/5/22 Wednesday 11:25:43,"[{'box': [1651.6944580078125, 356.920745849609..."
2,6,2024/5/22 Wednesday 11:25:43,"[{'box': [1651.7314453125, 355.41156005859375,..."
3,9,2024/5/22 Wednesday 11:25:43,"[{'box': [1651.772216796875, 355.3622436523437..."
4,12,2024/5/22 Wednesday 11:25:43,"[{'box': [1651.79248046875, 355.15875244140625..."

In [7]:
dataframe2.results[0]

"[{'box': [1651.468505859375, 360.8627014160156, 80.3453369140625, 239.0478515625], 'conf': 0.65324163, 'label_id': 'person', 'sub_labels': 'other', 'sub_labels_conf': 0.996187150478363, 'id': 106407}, {'box': [1438.12353515625, 262.52099609375, 98.6126708984375, 169.6667022705078], 'conf': 0.7459576, 'label_id': 'person', 'sub_labels': 'other', 'sub_labels_conf': 0.9999827146530151, 'id': 106474}, {'box': [1500.005126953125, 221.4818115234375, 64.964111328125, 72.99409484863281], 'conf': 0.32406616, 'label_id': 'person', 'sub_labels': 'other', 'sub_labels_conf': 0.9981861710548401, 'id': 106467}, {'box': [555.2720336914062, 185.5115966796875, 72.21630859375, 106.01753234863281], 'conf': 0.7465232, 'label_id': 'person', 'sub_labels': 'other', 'sub_labels_conf': 1.0, 'id': 106503}, {'box': [202.52835083007812, 379.8591613769531, 142.6361541748047, 283.67474365234375], 'conf': 0.8923002, 'label_id': 'person', 'sub_labels': 'other', 'sub_labels_conf': 0.9999663829803467, 'id': 106505}, {'box': [795.7998046875, 110.69573974609375, 67.88397216796875, 72.67233276367188], 'conf': 0.5112966, 'label_id': 'person', 'sub_labels': 'other', 'sub_labels_conf': 0.9999880790710449, 'id': 106507}]"